version: '3'
services:
  archon:
    image: archon:latest
    ports:
      - "8888:80"
    depends_on:
      - db
  archivesspace:
    image: archivesspace/archivesspace:2.6.0
    ports:
      - "8089:8089"
    depends_on:
      - db
    restart: on-failure
    environment:
      APPCONFIG_DB_URL: 'jdbc:mysql://db:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123'
      APPCONFIG_ENABLE_DOCS: "false"
      APPCONFIG_ENABLE_FRONTEND: "false"
      APPCONFIG_ENABLE_INDEXER: "false"
      APPCONFIG_ENABLE_OAI: "false"
      APPCONFIG_ENABLE_PUBLIC: "false"
      APPCONFIG_ENABLE_SOLR: "false"
      ASPACE_JAVA_XMX: -Xmx2048m
  db:
    image: mysql:5.7
    command: >
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
      --innodb_buffer_pool_size=2G
      --innodb_buffer_pool_instances=2
      --lower_case_table_names=1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: archon
      MYSQL_USER: archon
      MYSQL_PASSWORD: archon
    volumes:
      - ./archivesspace.sql:/docker-entrypoint-initdb.d/archivesspace.sql
      - ./archon.sql:/docker-entrypoint-initdb.d/archon.sql
